### ISSUE TITLE
Set radius units

### ISSUE THREAD

**Issue by robert-hatfield** [pavelpark/location-reminder#33]
Work started on ad4b8d0.

**TODO:**
- [x] Convert the value in the text field back into meters when the reminder is created.
- [x] Improve formatting for decimal numbers. We'll probably want to round to the nearest whole number for m and ft.
- [x] Use a decimal keypad for km & mi.

**Comment by robert-hatfield** [comment]
- [x] Add the notification observer back to **ViewController.m** - it got lost in one of the merges.
  - `[[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(removeOverlayForNotification:) name:@"Reminder completed" object:nil];`
